### ISSUE TITLE
Fetch cocktail API for random cocktails

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#13]
## Description 
We need to call the cocktail API to get some cool cocktail recipes.

![Screen Shot 2021-04-24 at 4 07 10 PM](https://user-images.githubusercontent.com/79773301/115975152-29db4980-a517-11eb-9794-d181ff0cbce2.png)

## Needed
- When the 'Random' button is clicked, call the 'Random' cocktail API.

##
From https://www.thecocktaildb.com/api.php:

_Lookup a random cocktail_
www.thecocktaildb.com/api/json/v1/1/random.php

**Comment by pablodlc** [comment]
The API call is functional.  Moving on to displaying the drink stuff on the DOM
