### ISSUE TITLE
Display Cocktail APIs random drink

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#14]
## Description

We need to figure out how we want to display the random cocktail, I was thinking of displaying it in the card (highlighted in pink):
![Screen Shot 2021-04-24 at 4 11 27 PM](https://user-images.githubusercontent.com/79773301/115975257-f8af4900-a517-11eb-9354-6d74782d2a42.png)

## Needed 
- Title of drink 
- Recipe 
** I don't think we need to have a picture of the cocktail but this is still uncertain until we are able to verify what the API gives us in return when we click the 'Random' button. Once we figure that out, we can try to display it in the card hopefully 🤞 so that way we don't have to build anything else.

**Comment by pablodlc** [comment]
Donezo!
