### ISSUE TITLE
Exit Trivia Game Modal 

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#32]
## Description

Currently, you cannot exit the trivia game modal. 

## Needed:
We need to create an 'X' button once clicked, exits the modal.  This should be the only way to exit the modal.

**Comment by Shilohjones194** [comment]
![image](https://user-images.githubusercontent.com/76697212/116797223-307a3b80-aa98-11eb-8532-098e6669b1ff.png)

It has been added and styled a bit.
