### ISSUE TITLE
Players End Score

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#33]
## Description 

We need to fix the player's end score.

## Needed:
- After the Trivia Game questions have been completed, we need to clear the content in the modal.
- Display player's final score 
- Allow player to add initials
- Add 'Submit Score' button (to save to local storage, high scores will be displayed on the landing page)

**Comment by Shilohjones194** [comment]
Lily completed first two were completed. Was not able to complete the last 2 requests for submitting score and adding players initials.
