### ISSUE TITLE
Welcome Message 

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#6]
## Description
Create a welcome message for the landing/home page. 

- Short (and possibly funny/dorky) welcome message to welcome the players 
- Will be located in the center of the page, marked in pink below:
![Screen Shot 2021-04-23 at 8 40 59 PM](https://user-images.githubusercontent.com/79773301/115946194-7457ba00-a474-11eb-89db-c64e6757b86e.png)

**Comment by Shilohjones194** [comment]
MVP for the Welcome message has been created:
![image](https://user-images.githubusercontent.com/76697212/115974132-6e62e700-a50f-11eb-955a-6afaac10b117.png)
