### ISSUE TITLE
Rules/explanation of game

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#7]
## Description 
Short explanation of the rules.

Must include:

- Letting the player know they must make a drink before starting the game ("Click to your right to make a drink!").
- The option of selecting a drink by liquor or 'random' can be explained here in this section too
- Info on how you get points deducted when you get a trivia question wrong 
- User with the highest points wins
- Trivia category info

![Screen Shot 2021-04-23 at 8 40 59 PM](https://user-images.githubusercontent.com/79773301/115946478-4b382900-a476-11eb-9a66-31b735f04534.png)

## Needed

We still need to decide what our trivia category will be so we can inform the players beforehand. Unless we can somehow allow them to select 'random' trivia categories when we call the trivia API.

**Comment by Shilohjones194** [comment]
The 2nd section has been added but defiantly needs more work and possibly a different API from what we were using. The Current one we have chose does not keep track of scores. 
But to make it simple, I just made it, if you get it wrong you, drink. Simple but yet effective.
![image](https://user-images.githubusercontent.com/76697212/115974146-86d30180-a50f-11eb-9929-850bacdf1275.png)

**Comment by lilyhi** [comment]
I like it! Let's also include something like - "Player with the highest score wins". And omg at the TWAT button 😆 

Regarding keeping track of scores, we will have to build that with JavaScript once the game is started. Similar to how we did the Quiz Code Challenge.
