### ISSUE TITLE
Start Button

### ISSUE THREAD

**Issue by lilyhi** [Shilohjones194/Project1#8]
## Description 
Make the Start (game) button. Clicking the 'Start' button should then start the game on the second page we create/or the other option is to remove the first page's elements. Still need to decide. Possibly the latter? 
![Screen Shot 2021-04-23 at 8 57 18 PM](https://user-images.githubusercontent.com/79773301/115946594-2b553500-a477-11eb-8a8e-c9a8578f21bf.png)

After clicking the 'Start' button the page should then look like this:
![Screen Shot 2021-04-23 at 9 02 50 PM](https://user-images.githubusercontent.com/79773301/115946611-488a0380-a477-11eb-9b44-ababc1ce583e.png)

**Comment by Shilohjones194** [comment]
Start button has been made within HTML. Button id is "Start Trivia". STill working on the 2nd module page

**Comment by Shilohjones194** [comment]
Button has been added, but now needs to be styled.
![image](https://user-images.githubusercontent.com/76697212/116490422-3380ec00-a84c-11eb-90f6-60d39a3a524e.png)
